# Generated by Django 4.1 on 2022-08-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=255, verbose_name='Todo')),
                ('contents', models.CharField(max_length=255, verbose_name='content')),
            ],
        ),
    ]
