# Generated by Django 4.1 on 2022-08-31 17:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('todo', models.CharField(max_length=255, verbose_name='Todo')),
                ('contents', models.TextField(max_length=255, verbose_name='content')),
                ('created_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
